language: android
jdk: oraclejdk8
android:
        components:
                - platform-tools
                - build-tools-25.0.2
                - android-25
        script:
                - ./gradlew build
        before_install:
                - chmod +x gradlew
